#!/bin/bash
sudo stdbuf -o0 od -tx1 /dev/input/event0 | \
stdbuf -o0 awk -Winteractive \
	'$10 == "01" {
		if ($14 == "01") {
			print "pressed "$12
		}
		else if ($14 == "02") {
			print "autorepeated "$12
		} else print "released "$12
	}' \
| while read line; do echo "$(date +%s.%3N) : $line"; done \
> keys
