#!/bin/bash

while :
do
	echo "test"
	# echo $(sudo stdbuf -o0 od -tx1 /dev/input/event0 | stdbuf -o0 grep '.40 ' | stdbuf -o0 awk -Winteractive '{print $12}')
	echo $(sudo od -tx1 /dev/input/event0)
done
